name: Markdown Checks
### https://github.com/harmless-tech/rust-github-actions

on:
    push:
        branches: [ main ]
        # paths: [ .github/workflows/markdown-checks.yml, .typos.toml, docs/**, "*.md" ]
    pull_request:
        branches: [ main ]
        # paths: [ .github/workflows/markdown-checks.yml, .typos.toml, docs/**, "*.md" ]
    workflow_dispatch:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master
